import { readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadFixture, replayAttempts, type Fixture } from './replay.js';
import {
  computeConvergence,
  computeSegments,
  computeVerdict,
  computeCorpusVerdict,
  type FixtureSummary,
} from './metrics.js';

const HERE = dirname(fileURLToPath(import.meta.url));

function fixtureDirs(): string[] {
  return readdirSync(HERE, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(HERE, d.name, 'attempts.json')))
    .map((d) => d.name)
    .sort();
}

export interface CorpusRunResult {
  corpusSummaries: FixtureSummary[];
  driftCount: number;
  selftestOk: boolean;
  resultsMarkdown: string;
}

/**
 * Pure-ish core: replays a set of already-loaded fixtures through the live
 * validator and derives all metrics + the RESULTS.md body. No process.exit,
 * no file I/O — so it is unit-testable. A fixture is treated as a self-test
 * when its fixtureId starts with `_selftest`.
 */
export function runCorpus(fixtures: Fixture[]): CorpusRunResult {
  const corpusSummaries: FixtureSummary[] = [];
  const lines: string[] = [];
  let driftCount = 0;
  let selftestOk = true;

  lines.push('# Dogfood proof corpus — results', '');
  lines.push('Generated by `npm run dogfood:corpus`. Numbers come from the live `verifyManifest()`.', '');

  for (const fx of fixtures) {
    const isSelftest = fx.fixtureId.startsWith('_selftest');
    const { results, drift } = replayAttempts(fx.attempts);
    const conv = computeConvergence(results);
    const segs = computeSegments(results);
    const verdict = computeVerdict(results);
    driftCount += drift.length;

    lines.push(`## ${fx.fixtureId}${isSelftest ? ' (self-test)' : ''}`);
    lines.push(`- shape: ${fx.shape} · skill: ${fx.skillArm} · difficulty: ${fx.difficulty} · trap: ${fx.trap ?? 'none'}`);
    lines.push(`- verdict: **${verdict.kind}** — ${verdict.reason}`);
    lines.push(`- total round-trips: ${conv.totalRoundTrips ?? 'did not converge'}`);
    lines.push('- segments:');
    for (const s of segs) {
      lines.push(`  - \`${s.cluster}\`: ${s.roundTripsSpent} round-trip(s), resolved at attempt ${s.resolvedAtAttempt ?? 'never'}`);
    }
    if (drift.length > 0) {
      lines.push(`- ⚠️ DRIFT on ${drift.length} attempt(s): the live validator disagrees with the recorded outcome.`);
    }
    lines.push('');

    if (isSelftest) {
      if (verdict.kind !== 'FAIL') selftestOk = false;
    } else {
      corpusSummaries.push({ fixtureId: fx.fixtureId, shape: fx.shape, skillArm: fx.skillArm, verdict });
    }
  }

  const cv = computeCorpusVerdict(corpusSummaries);
  lines.push('## Corpus verdict', '');
  lines.push(`- skill-on median round-trips: ${cv.skillOnMedian ?? 'n/a'}`);
  lines.push(`- skill-off median round-trips: ${cv.skillOffMedian ?? 'n/a'}`);
  lines.push(`- kill condition fired: **${cv.killConditionFired ? 'YES' : 'no'}** — ${cv.reason}`);
  lines.push(`- total drift across corpus: ${driftCount}`);
  lines.push('');

  return { corpusSummaries, driftCount, selftestOk, resultsMarkdown: lines.join('\n') };
}

/**
 * The exit decision, as a pure function of the run result. Two independent
 * invariants make the run non-green: a self-test fixture that did not FAIL, and
 * any drift (a recorded outcome the live validator no longer reproduces — the
 * spec requires the run be non-green until reconciled). Returns the messages to
 * print plus the process exit code so neither guard can silently override the
 * other and so the decision is unit-testable without spawning the script.
 */
export function corpusExitDecision(
  result: Pick<CorpusRunResult, 'driftCount' | 'selftestOk'>
): { code: number; messages: string[] } {
  const messages: string[] = [];
  if (!result.selftestOk) {
    messages.push('SELF-TEST FAILED: a _selftest fixture did not report FAIL. The harness cannot be trusted to emit bad results.');
  }
  if (result.driftCount > 0) {
    messages.push(`DRIFT DETECTED: ${result.driftCount} attempt(s) where the live validator disagrees with the recorded outcome. The run is non-green until reconciled.`);
  }
  return { code: messages.length > 0 ? 1 : 0, messages };
}

/** Thin I/O + exit wrapper around the pure core. */
function main(): void {
  const fixtures = fixtureDirs().map((name) => loadFixture(join(HERE, name)));
  const result = runCorpus(fixtures);
  const cv = computeCorpusVerdict(result.corpusSummaries);

  // Artifact must persist even on a failing run — write before any exit.
  writeFileSync(join(HERE, 'RESULTS.md'), result.resultsMarkdown, 'utf8');

  console.log(`Corpus: ${result.corpusSummaries.length} fixture(s); kill condition ${cv.killConditionFired ? 'FIRED' : 'not fired'}; drift ${result.driftCount}.`);

  const { code, messages } = corpusExitDecision(result);
  for (const m of messages) console.error(m);
  if (code !== 0) process.exit(code);
}

main();
