import { readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadFixture, replayAttempts } from './replay.js';
import {
  computeConvergence,
  computeSegments,
  computeVerdict,
  computeCorpusVerdict,
  type FixtureSummary,
} from './metrics.js';

const HERE = dirname(fileURLToPath(import.meta.url));

function fixtureDirs(): string[] {
  return readdirSync(HERE, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(HERE, d.name, 'attempts.json')))
    .map((d) => d.name)
    .sort();
}

function main(): void {
  const corpusSummaries: FixtureSummary[] = [];
  const lines: string[] = [];
  let driftCount = 0;
  let selftestOk = true;

  lines.push('# Dogfood proof corpus — results', '');
  lines.push('Generated by `npm run dogfood:corpus`. Numbers come from the live `verifyManifest()`.', '');

  for (const name of fixtureDirs()) {
    const isSelftest = name.startsWith('_selftest');
    const fx = loadFixture(join(HERE, name));
    const { results, drift } = replayAttempts(fx.attempts);
    const conv = computeConvergence(results);
    const segs = computeSegments(results);
    const verdict = computeVerdict(results);
    driftCount += drift.length;

    lines.push(`## ${fx.fixtureId}${isSelftest ? ' (self-test)' : ''}`);
    lines.push(`- shape: ${fx.shape} · skill: ${fx.skillArm} · difficulty: ${fx.difficulty} · trap: ${fx.trap ?? 'none'}`);
    lines.push(`- verdict: **${verdict.kind}** — ${verdict.reason}`);
    lines.push(`- total round-trips: ${conv.totalRoundTrips ?? 'did not converge'}`);
    lines.push('- segments:');
    for (const s of segs) {
      lines.push(`  - \`${s.cluster}\`: ${s.roundTripsSpent} round-trip(s), resolved at attempt ${s.resolvedAtAttempt ?? 'never'}`);
    }
    if (drift.length > 0) {
      lines.push(`- ⚠️ DRIFT on ${drift.length} attempt(s): the live validator disagrees with the recorded outcome.`);
    }
    lines.push('');

    if (isSelftest) {
      if (verdict.kind !== 'FAIL') selftestOk = false;
    } else {
      corpusSummaries.push({ fixtureId: fx.fixtureId, shape: fx.shape, skillArm: fx.skillArm, verdict });
    }
  }

  const cv = computeCorpusVerdict(corpusSummaries);
  lines.push('## Corpus verdict', '');
  lines.push(`- skill-on median round-trips: ${cv.skillOnMedian ?? 'n/a'}`);
  lines.push(`- skill-off median round-trips: ${cv.skillOffMedian ?? 'n/a'}`);
  lines.push(`- kill condition fired: **${cv.killConditionFired ? 'YES' : 'no'}** — ${cv.reason}`);
  lines.push(`- total drift across corpus: ${driftCount}`);
  lines.push('');

  writeFileSync(join(HERE, 'RESULTS.md'), lines.join('\n'), 'utf8');

  // Console summary + non-zero exit on a broken invariant, so the runner is CI-honest.
  console.log(`Corpus: ${corpusSummaries.length} fixture(s); kill condition ${cv.killConditionFired ? 'FIRED' : 'not fired'}; drift ${driftCount}.`);
  if (!selftestOk) {
    console.error('SELF-TEST FAILED: a _selftest fixture did not report FAIL. The harness cannot be trusted to emit bad results.');
    process.exit(1);
  }
}

main();
